import { Geist_Mono, Zalando_Sans_Expanded } from "next/font/google";
import "./globals.css";

const zalandoSans = Zalando_Sans_Expanded({
  variable: "--font-zalando-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Scroll Reactive Marquee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${zalandoSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
